//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LethalCompanyModHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class I18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LethalCompanyModHelper.Properties.I18n", typeof(I18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Author.
        /// </summary>
        internal static string FormMain_AboutModAuthor {
            get {
                return ResourceManager.GetString("FormMain/AboutModAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string FormMain_AboutSoftwareAuthor {
            get {
                return ResourceManager.GetString("FormMain/AboutSoftwareAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Update.
        /// </summary>
        internal static string FormMain_CheckModUpdate {
            get {
                return ResourceManager.GetString("FormMain/CheckModUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string FormMain_Error {
            get {
                return ResourceManager.GetString("FormMain/Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lethal Company Mod Helper -- by TinyMins.
        /// </summary>
        internal static string FormMain_FormTitle {
            get {
                return ResourceManager.GetString("FormMain/FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Folder.
        /// </summary>
        internal static string FormMain_GamePath {
            get {
                return ResourceManager.GetString("FormMain/GamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lethal Company Game Path Not Found!.
        /// </summary>
        internal static string FormMain_GamePathNotFoundError {
            get {
                return ResourceManager.GetString("FormMain/GamePathNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Folder.
        /// </summary>
        internal static string FormMain_GameSavePath {
            get {
                return ResourceManager.GetString("FormMain/GameSavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install MOD.
        /// </summary>
        internal static string FormMain_InstallMod {
            get {
                return ResourceManager.GetString("FormMain/InstallMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        internal static string FormMain_StartGame {
            get {
                return ResourceManager.GetString("FormMain/StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string FromInstall_FormTitle {
            get {
                return ResourceManager.GetString("FromInstall/FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select optional mod packs:.
        /// </summary>
        internal static string FromInstall_PleaseSelectOptionalModPacks_ {
            get {
                return ResourceManager.GetString("FromInstall/PleaseSelectOptionalModPacks:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Install.
        /// </summary>
        internal static string FromInstall_StartInstall {
            get {
                return ResourceManager.GetString("FromInstall/StartInstall", resourceCulture);
            }
        }
    }
}
